<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-BrunoCarmoS2004/blob/main/atividadeQueMario.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Treino de NumPy — 42 exercícios hands-on

**Objetivo:** praticar manipulação de arrays NumPy (criação, slicing, broadcasting, álgebra linear, estatística, datas, strides).
**Regras:** use **apenas** NumPy (`import numpy as np`). Para reprodutibilidade, prefira `np.random.default_rng(seed)`.


## Fáceis (24)

### 1. Vetor de zeros  _(fácil)_

Crie um array 1D com 10 zeros usando NumPy e mostre o dtype e o shape.


### 2. Vetor de uns  _(fácil)_

Crie um array 1D com 10 uns e transforme-o em float64.


### 3. Sequência 0–9  _(fácil)_

Crie um array com os inteiros de 0 a 9 (inclusive).


### 4. Matriz 3×3 com 0…8  _(fácil)_

Crie um array 3×3 com os valores 0…8 (reshape).


### 5. Índices não zero  _(fácil)_

Dado o vetor `v = np.array([1,2,0,0,4,0])`, encontre os índices dos elementos não nulos.


### 6. Linspace  _(fácil)_

Crie um vetor de 12 pontos igualmente espaçados no intervalo [0, 1].


### 7. Identidade 5×5  _(fácil)_

Crie uma matriz identidade de ordem 5.


### 8. Aleatórios 3×3×3  _(fácil)_

Gere um array 3×3×3 com valores aleatórios uniformes em [0,1). Use `np.random.default_rng(42)`.


### 9. Min/Max  _(fácil)_

Crie uma matriz 10×10 de aleatórios uniformes e mostre o valor mínimo e máximo.


### 10. Padronização 1D  _(fácil)_

Dado `x = [1,2,3,4,5]`, crie um array float e normalize para média 0 e desvio 1.


### 11. Conversão de tipos  _(fácil)_

Converta `np.array([1,2,3])` (int32) para float32 e depois para int64.


### 12. Clipping  _(fácil)_

Dado `a = [2, 5, 7, 1, 9]`, limite os valores ao intervalo [0,5] (valores acima de 5 tornam-se 5).


### 13. Inversão  _(fácil)_

Crie um vetor de 0 a 9 e inverta a ordem (sem usar `[::-1]`).


### 14. Empilhamento  _(fácil)_

Dado `a = [1,2,3]` e `b = [4,5,6]`, empilhe horizontal e verticalmente.


### 15. Diagonal  _(fácil)_

Crie uma matriz 4×4 com a diagonal principal igual a 5 e as demais entradas zero.


### 16. Somas por eixo  _(fácil)_

Para a matriz `A = np.arange(12).reshape(3,4)`, calcule a soma por linhas e por colunas.


### 17. Frequências inteiras  _(fácil)_

Gere 100 inteiros aleatórios em [0,9] e conte as frequências de cada valor (0 a 9).


### 18. Slicing com passo  _(fácil)_

Dado `v = np.arange(20)`, selecione cada 3º elemento começando do índice 1.


### 19. Máscara booleana  _(fácil)_

Crie uma máscara para números pares de `0…19` e use-a para filtrar o vetor.


### 20. Lista de listas → array  _(fácil)_

Converta `[[1,2,3],[4,5,6]]` em `ndarray`, verifique `shape` e `dtype`.


### 21. Datas básicas  _(fácil)_

Crie um array de datas diárias de 2025-01-01 a 2025-01-07 (inclusive).


### 22. Centralizar colunas  _(fácil)_

Dada `A = np.array([[1.,2.,3.],[4.,5.,6.]])`, subtraia a média de cada coluna.


### 23. Produto elemento-a-elemento vs. escalar  _(fácil)_

Dadas `a=[1,2,3]` e `b=[4,5,6]`, calcule produto elemento a elemento e o produto escalar.


### 24. Troca de colunas  _(fácil)_

Troque as colunas 0 e 2 de `A = np.arange(12).reshape(3,4)` sem copiar (sempre que possível).



## Médios (12)

### 25. Flatten vs. ravel  _(médio)_

Mostre a diferença entre `flatten()` (cópia) e `ravel()` (view quando possível). Modifique o resultado de `ravel()` e observe o original.


### 26. Tabuleiro 8×8  _(médio)_

Crie uma matriz 8×8 com padrão de tabuleiro (0 e 1 alternados).


### 27. np.where condicional  _(médio)_

Dado `x = np.arange(-5,6)`, substitua negativos por 0 e mantenha não-negativos.


### 28. Precisão de média  _(médio)_

Gere 1_000_000 floats uniformes em [0,1) e compute a média. Compare com o valor teórico 0.5 (erro absoluto).


### 29. Produto cartesiano (broadcasting)  _(médio)_

Dado `a=[1,2,3]` e `b=[10,20,30,40]`, gere todas as somas possíveis `a_i + b_j` via broadcasting (matriz 3×4).


### 30. Convolução 1D simples  _(médio)_

Implemente uma convolução 1D 'valid' de um sinal `s` por um kernel `k` usando `np.flip` e `np.lib.stride_tricks.sliding_window_view` (sem `np.convolve`).


### 31. Normalização min–max por coluna  _(médio)_

Dada `A = rng.normal(size=(5,4))`, normalize cada coluna para o intervalo [0,1], tratando colunas constantes.


### 32. Ordenar por coluna  _(médio)_

Ordene as linhas de `A = np.array([[3,9],[1,4],[2,5]])` pelo valor crescente da 2ª coluna.


### 33. Únicos + contagens + primeira ocorrência  _(médio)_

Para `x = [3,1,2,3,2,3,1]`, obtenha valores únicos, contagens e índice da primeira ocorrência de cada valor.


### 34. Matriz de distâncias 2D  _(médio)_

Dada `P` com N pontos 2D, compute a matriz NxN de distâncias euclidianas sem loops explícitos.


### 35. Covariância e correlação  _(médio)_

Simule uma matriz 1000×3 de N(0,1) e compute `cov` (colunas como variáveis) e `corrcoef`.


### 36. One-hot encoding  _(médio)_

Converta os rótulos `y = [2,0,1,2]` em codificação one-hot usando apenas operações NumPy.



## Difíceis (6)

### 37. k-means 2D (NumPy puro)  _(difícil)_

Implemente k-means com K=3 em pontos 2D: inicialize centróides aleatórios, faça 10 iterações de (1) atribuir pontos ao centróide mais próximo e (2) recomputar centróides.


### 38. PCA básica (autovetores)  _(difícil)_

Implemente PCA 2D→1D: centralize `X` (N×2), calcule covariância, autovetores, projete em 1D e reconstrua aproximado.


### 39. Convolução 2D (im2col)  _(difícil)_

Implemente convolução 2D 'valid' de uma imagem `I` por um kernel `K` usando `sliding_window_view` para gerar blocos e multiplicação matricial.


### 40. Sistemas lineares e resíduo  _(difícil)_

Gere uma matriz A (100×100) bem-condicionada, um vetor b e resolva `Ax=b` com `np.linalg.solve`. Compute o resíduo relativo `||Ax−b||/||b||` e `cond(A)`.


### 41. Regressão linear (OLS) com NumPy  _(difícil)_

Dado `X` (N×d) e `y`, calcule os coeficientes OLS usando `np.linalg.lstsq` e avalie RMSE no treino.


### 42. Rolling window 2D com strides  _(difícil)_

Usando `sliding_window_view`, compute a média local 3×3 de uma imagem 2D sem laços explícitos.

In [1]:
import numpy as np

### 1. Vetor de zeros  _(fácil)_

Crie um array 1D com 10 zeros usando NumPy e mostre o dtype e o shape.

In [ ]:
array = np.zeros(10)
print(array.dtype)
print(array.shape)

float64
(10,)


### 2. Vetor de uns  _(fácil)_

Crie um array 1D com 10 uns e transforme-o em float64.

In [ ]:
array = np.ones(10)
array = np.float64(array)
print(array.dtype)

float64


### 3. Sequência 0–9  _(fácil)_

Crie um array com os inteiros de 0 a 9 (inclusive).

In [ ]:
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


### 4. Matriz 3×3 com 0…8  _(fácil)_

Crie um array 3×3 com os valores 0…8 (reshape).

In [ ]:
array = np.arange(9).reshape((3,3))
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 5. Índices não zero  _(fácil)_

Dado o vetor `v = np.array([1,2,0,0,4,0])`, encontre os índices dos elementos não nulos.


In [ ]:
v = np.array([1,2,0,0,4,0])
v = np.where(v == 0)
print(v)

(array([2, 3, 5]),)


### 6. Linspace  _(fácil)_

Crie um vetor de 12 pontos igualmente espaçados no intervalo [0, 1].

In [ ]:
v = np.arange(0, 12, 1)
print(v)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


### 7. Identidade 5×5  _(fácil)_

Crie uma matriz identidade de ordem 5.


In [ ]:
v = np.eye(5)
print(v)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 8. Aleatórios 3×3×3  _(fácil)_

Gere um array 3×3×3 com valores aleatórios uniformes em [0,1). Use `np.random.default_rng(42)`.

In [ ]:


random_array = np.random.default_rng(42).random((3, 3, 3))
print(random_array)

[[[0.77395605 0.43887844 0.85859792]
  [0.69736803 0.09417735 0.97562235]
  [0.7611397  0.78606431 0.12811363]]

 [[0.45038594 0.37079802 0.92676499]
  [0.64386512 0.82276161 0.4434142 ]
  [0.22723872 0.55458479 0.06381726]]

 [[0.82763117 0.6316644  0.75808774]
  [0.35452597 0.97069802 0.89312112]
  [0.7783835  0.19463871 0.466721  ]]]


### 9. Min/Max  _(fácil)_

Crie uma matriz 10×10 de aleatórios uniformes e mostre o valor mínimo e máximo.

In [ ]:
v = np.random.rand(10, 10)
print(v)
min = np.min(v)
max = np.max(v)
print(min)
print(max)

[[0.0922307  0.7655112  0.46749211 0.24219907 0.37620305 0.31247263
  0.41391738 0.13292747 0.2226188  0.31212787]
 [0.68851457 0.16156395 0.32885278 0.23373819 0.75561552 0.77587845
  0.19115534 0.13477572 0.5321893  0.08680689]
 [0.72536757 0.08450703 0.31547455 0.86353712 0.55411719 0.03545875
  0.4054754  0.91976935 0.72473943 0.01525416]
 [0.91740434 0.58380865 0.06211212 0.23031035 0.65687001 0.88918341
  0.56491995 0.12807204 0.61595064 0.78331501]
 [0.8240524  0.35094288 0.72568104 0.09667404 0.82119186 0.42265573
  0.39876479 0.30663361 0.73638825 0.47115207]
 [0.0051562  0.96231961 0.77769218 0.98395348 0.09470388 0.25643968
  0.2660106  0.88234016 0.18199335 0.06003447]
 [0.30510101 0.21349685 0.34395456 0.41024358 0.29291978 0.7453171
  0.88318638 0.04434351 0.27268337 0.26237149]
 [0.08534524 0.31447406 0.08070911 0.75300483 0.9026865  0.680671
  0.06556933 0.00853405 0.38071013 0.83237242]
 [0.93778281 0.67535392 0.30277878 0.4010867  0.93279948 0.35805935
  0.65087629 0.

### 10. Padronização 1D  _(fácil)_

Dado `x = [1,2,3,4,5]`, crie um array float e normalize para média 0 e desvio 1.

In [ ]:
v = np.array([1,2,3,4,5])
media = v.mean()
desvio = v.std()
v = (v - media) / desvio
print(v)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


### 11. Conversão de tipos  _(fácil)_

Converta `np.array([1,2,3])` (int32) para float32 e depois para int64.

In [ ]:
v = np.array([1,2,3], dtype=np.uint32)
print(v)
v = np.array(v, dtype= np.float32)
print(v)
v = np.array(v, dtype=np.uint64)
print(v)


[1 2 3]
[1. 2. 3.]
[1 2 3]


### 12. Clipping  _(fácil)_

Dado `a = [2, 5, 7, 1, 9]`, limite os valores ao intervalo [0,5] (valores acima de 5 tornam-se 5).

In [ ]:
v = np.array([2,5,7,1,9])
v = np.clip(v, 0, 5)
print(v)

[2 5 5 1 5]


### 13. Inversão  _(fácil)_

Crie um vetor de 0 a 9 e inverta a ordem (sem usar `[::-1]`).


In [ ]:
v = np.arange(10)
print(v)
v = np.flip(v)
print(v)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


### 14. Empilhamento  _(fácil)_

Dado `a = [1,2,3]` e `b = [4,5,6]`, empilhe horizontal e verticalmente.

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
v = np.block([[a],[b]])
print(v)

[[1 2 3]
 [4 5 6]]


### 15. Diagonal  _(fácil)_

Crie uma matriz 4×4 com a diagonal principal igual a 5 e as demais entradas zero.

In [ ]:
v = np.diag([5, 5, 5, 5])
print(v)

[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 5 0]
 [0 0 0 0 6]]


### 16. Somas por eixo  _(fácil)_

Para a matriz `A = np.arange(12).reshape(3,4)`, calcule a soma por linhas e por colunas.

In [ ]:
v = np.arange(12).reshape(3, 4)
linhas = v.sum(axis=1)
colunas = v.sum(axis=0)
print(v)
print(linhas)
print(colunas)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 6 22 38]
[12 15 18 21]


### 17. Frequências inteiras  _(fácil)_

Gere 100 inteiros aleatórios em [0,9] e conte as frequências de cada valor (0 a 9)

In [ ]:
v = np.random.randint(0, 10, 100)
f = np.bincount(v, minlength=10)
print(v)
print(f)


[6 3 6 3 4 5 5 6 9 3 8 7 0 9 3 6 9 5 1 0 0 4 2 9 2 2 4 7 1 2 5 6 0 1 1 6 4
 5 7 8 8 4 5 7 4 3 0 9 7 0 0 9 9 8 2 4 0 2 8 7 0 0 5 4 9 8 0 0 8 9 2 2 4 9
 2 9 4 8 7 1 8 0 0 3 4 9 6 3 5 1 8 4 9 9 5 0 3 6 3 5]
[15  6  9  9 12 10  8  7 10 14]


### 18. Slicing com passo  _(fácil)_

Dado `v = np.arange(20)`, selecione cada 3º elemento começando do índice 1.

In [ ]:

v = np.arange(20)
r = v[1::3]
print(v)
print(r)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  4  7 10 13 16 19]


### 19. Máscara booleana  _(fácil)_

Crie uma máscara para números pares de `0…19` e use-a para filtrar o vetor.

In [ ]:
v = np.arange(20)
m = v % 2 == 0
v[m]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


### 20. Lista de listas → array  _(fácil)_

Converta `[[1,2,3],[4,5,6]]` em `ndarray`, verifique `shape` e `dtype`.

In [ ]:
l = [[1,2,3],[4,5,6]]
a = np.array(l)
print(a.shape)
print(a.dtype)

(2, 3)
int64


### 21. Datas básicas  _(fácil)_

Crie um array de datas diárias de 2025-01-01 a 2025-01-07 (inclusive).


In [ ]:
d = np.arange('2025-01-01', '2025-01-08', dtype='datetime64[D]')
print(d)

['2025-01-01' '2025-01-02' '2025-01-03' '2025-01-04' '2025-01-05'
 '2025-01-06' '2025-01-07']


### 22. Centralizar colunas  _(fácil)_

Dada `A = np.array([[1.,2.,3.],[4.,5.,6.]])`, subtraia a média de cada coluna.

In [ ]:
a = np.array([[1.,2.,3.],[4.,5.,6.]])
a - a.mean(axis=0)
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]


### 23. Produto elemento-a-elemento vs. escalar  _(fácil)_

Dadas `a=[1,2,3]` e `b=[4,5,6]`, calcule produto elemento a elemento e o produto escalar.


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a * b)
print(a @ b)


[ 4 10 18]
32


### 24. Troca de colunas  _(fácil)_

Troque as colunas 0 e 2 de `A = np.arange(12).reshape(3,4)` sem copiar (sempre que possível).

In [ ]:
a = np.arange(12).reshape(3,4)
a[:, [0, 2]] = a[:, [2, 0]]
print(a)

[[ 2  1  0  3]
 [ 6  5  4  7]
 [10  9  8 11]]


## Médios (12)

### 25. Flatten vs. ravel  _(médio)_

Mostre a diferença entre `flatten()` (cópia) e `ravel()` (view quando possível). Modifique o resultado de `ravel()` e observe o original.


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
f = a.flatten()
r = a.ravel()
r[0] = 99
print(a)
print(f)
print(r)

[[99  2  3]
 [ 4  5  6]]
[1 2 3 4 5 6]
[99  2  3  4  5  6]


### 26. Tabuleiro 8×8  _(médio)_

Crie uma matriz 8×8 com padrão de tabuleiro (0 e 1 alternados).

In [ ]:
t = np.zeros((8,8), dtype=int)
t[1::2, ::2] = 1
t[::2, 1::2] = 1
print(t)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 27. np.where condicional  _(médio)_

Dado `x = np.arange(-5,6)`, substitua negativos por 0 e mantenha não-negativos.

In [ ]:
x = np.arange(-5, 6)
print(np.where(x < 0, 0, x))

[0 0 0 0 0 0 1 2 3 4 5]


### 28. Precisão de média  _(médio)_

Gere 1_000_000 floats uniformes em [0,1) e compute a média. Compare com o valor teórico 0.5 (erro absoluto).

In [ ]:
x = np.random.rand(1_000_000)
m = x.mean()
e = abs(m - 0.5)
print(m, e)

0.5000425142732954 4.251427329537982e-05


### 29. Produto cartesiano (broadcasting)  _(médio)_

Dado `a=[1,2,3]` e `b=[10,20,30,40]`, gere todas as somas possíveis `a_i + b_j` via broadcasting (matriz 3×4).

In [ ]:
a = np.array([1,2,3])
b = np.array([10,20,30,40])
print(a[:, None] + b)

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


### 30. Convolução 1D simples  _(médio)_

Implemente uma convolução 1D 'valid' de um sinal `s` por um kernel `k` usando `np.flip` e `np.lib.stride_tricks.sliding_window_view` (sem `np.convolve`).

In [ ]:
s = np.array([1,2,3,4,5])
k = np.array([1,0,-1])
w = np.lib.stride_tricks.sliding_window_view(s, k.size)
r = (w * np.flip(k)).sum(axis=1)
print(r)

[2 2 2]



### 31. Normalização min–max por coluna  _(médio)_

Dada `A = rng.normal(size=(5,4))`, normalize cada coluna para o intervalo [0,1], tratando colunas constantes.

In [ ]:
randum = np.random.default_rng()
a = randum.normal(size=(5,4))
mn = a.min(axis=0)
mx = a.max(axis=0)
r = mx - mn
r[r == 0] = 1
print((a - mn) / r)

[[0.74380465 0.37175103 0.         0.        ]
 [0.         1.         0.21722978 0.21292599]
 [1.         0.         0.2021919  0.26777395]
 [0.98876598 0.37554674 0.06553795 0.80125264]
 [0.90167976 0.32695517 1.         1.        ]]


### 32. Ordenar por coluna  _(médio)_

Ordene as linhas de `A = np.array([[3,9],[1,4],[2,5]])` pelo valor crescente da 2ª coluna.


In [ ]:
a = np.array([[3,9],[1,4],[2,5]])
print(a[a[:,1].argsort()])

[[1 4]
 [2 5]
 [3 9]]


### 33. Únicos + contagens + primeira ocorrência  _(médio)_

Para `x = [3,1,2,3,2,3,1]`, obtenha valores únicos, contagens e índice da primeira ocorrência de cada valor.

In [ ]:
x = np.array([3,1,2,3,2,3,1])
u, i, c = np.unique(x, return_index=True, return_counts=True)
print(u, i, c)

[1 2 3] [1 2 0] [2 2 3]



### 34. Matriz de distâncias 2D  _(médio)_

Dada `P` com N pontos 2D, compute a matriz NxN de distâncias euclidianas sem loops explícitos.


In [ ]:
p = np.random.rand(5, 2)
d = np.sqrt(((p[:, None, :] - p[None, :, :]) ** 2).sum(axis=2))
print(d)

[[0.         1.0533286  0.69684879 0.83872193 0.52382653]
 [1.0533286  0.         0.380242   0.53553894 0.54029585]
 [0.69684879 0.380242   0.         0.3173953  0.24981939]
 [0.83872193 0.53553894 0.3173953  0.         0.5391791 ]
 [0.52382653 0.54029585 0.24981939 0.5391791  0.        ]]


### 35. Covariância e correlação  _(médio)_

Simule uma matriz 1000×3 de N(0,1) e compute `cov` (colunas como variáveis) e `corrcoef`.

In [ ]:
randum = np.random.default_rng()
a = randum.standard_normal((1000, 3))
cov = np.cov(A, rowvar=False)
corr = np.corrcoef(A, rowvar=False)
print(cov, corr)

[[1.  2.5]
 [2.5 7. ]] [[1.         0.94491118]
 [0.94491118 1.        ]]


### 36. One-hot encoding  _(médio)_

Converta os rótulos `y = [2,0,1,2]` em codificação one-hot usando apenas operações NumPy.

In [ ]:
y = np.array([2,0,1,2])
n = y.max() + 1
o = np.eye(n)[y]
print(o)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 37. k-means 2D (NumPy puro)  _(difícil)_

Implemente k-means com K=3 em pontos 2D: inicialize centróides aleatórios, faça 10 iterações de (1) atribuir pontos ao centróide mais próximo e (2) recomputar centróides.

In [2]:
x = np.random.randn(150, 2) * 2 + np.array([2, 4])
x[:50] += np.array([5, -3])
x[50:100] += np.array([-4, 0])

k = 3
t = 10
r = np.random.default_rng(0)
n = x.shape[0]
j = r.choice(n, k, replace=False)
c = x[j].copy()

for i in range(t):
    d = ((x[:, None, :] - c[None, :, :])**2).sum(axis=2)
    l = d.argmin(axis=1)
    for u in range(k):
        a = x[l == u]
        if a.shape[0] > 0:
            c[u] = a.mean(axis=0)
        else:
            c[u] = x[r.integers(0, n)]

print(c)


[[-2.80080419  2.86980814]
 [ 6.32082138  1.23647935]
 [ 0.86944514  5.03616618]]



### 38. PCA básica (autovetores)  _(difícil)_

Implemente PCA 2D→1D: centralize `X` (N×2), calcule covariância, autovetores, projete em 1D e reconstrua aproximado.

In [3]:
x = np.random.randn(200, 2) * 2 + np.array([3.0, -1.0])
m = x.mean(axis=0, keepdims=True)
y = x - m
s = (y.T @ y) / (y.shape[0] - 1)
e, u = np.linalg.eigh(s)
i = e.argmax()
p = u[:, i]
z = y @ p
r = z[:, None] @ p[None, :] + m
print(z[:5])
print(r[:5])


[ 2.83196303  1.64248283 -0.42456021  1.93658042 -2.33683119]
[[ 3.50389111  1.80741225]
 [ 3.23374367  0.6490153 ]
 [ 2.76428954 -1.36401221]
 [ 3.30053731  0.9354276 ]
 [ 2.32998629 -3.22631213]]


### 39. Convolução 2D (im2col)  _(difícil)_

Implemente convolução 2D 'valid' de uma imagem `I` por um kernel `K` usando `sliding_window_view` para gerar blocos e multiplicação matricial.

In [6]:
from numpy.lib.stride_tricks import sliding_window_view as s
x = np.arange(1, 26, dtype=float).reshape(5, 5)
k = np.array([[1, 0, -1],
              [1, 0, -1],
              [1, 0, -1]], dtype=float)
w = s(x, k.shape)
c = w.reshape(-1, k.size)
f = k.reshape(-1, 1)
o = (c @ f).reshape(w.shape[0], w.shape[1])
print(o)


[[-6. -6. -6.]
 [-6. -6. -6.]
 [-6. -6. -6.]]


### 40. Sistemas lineares e resíduo  _(difícil)_

Gere uma matriz A (100×100) bem-condicionada, um vetor b e resolva `Ax=b` com `np.linalg.solve`. Compute o resíduo relativo `||Ax−b||/||b||` e `cond(A)`.

In [7]:
n = 100
p = np.random.default_rng(0)
m = p.standard_normal((n, n))
q, z = np.linalg.qr(m)
d = np.linspace(1.0, 3.0, n)
a = (q * d) @ q.T
b = p.standard_normal(n)
x = np.linalg.solve(a, b)
v = a @ x - b
e = np.linalg.norm(v) / np.linalg.norm(b)
c = np.linalg.cond(a)
print(e)
print(c)


4.78164471135892e-16
3.000000000000001


### 41. Regressão linear (OLS) com NumPy  _(difícil)_

Dado `X` (N×d) e `y`, calcule os coeficientes OLS usando `np.linalg.lstsq` e avalie RMSE no treino.

In [9]:
n, d = 200, 3
r = np.random.default_rng(0)
x = r.standard_normal((n, d))
y = x @ np.array([2.0, -1.0, 0.5]) + 3.0 + r.normal(0, 0.5, n)
z = np.c_[np.ones(n), x]
w, s, k, t = np.linalg.lstsq(z, y, rcond=None)
p = z @ w
e = np.sqrt(np.mean((p - y) ** 2))
print(w)
print(e)


[ 2.98193058  1.95500869 -1.0480763   0.52651279]
0.5000400414302021


### 42. Rolling window 2D com strides  _(difícil)_

Usando `sliding_window_view`, compute a média local 3×3 de uma imagem 2D sem laços explícitos.


In [10]:
from numpy.lib.stride_tricks import sliding_window_view as s
x = np.arange(1, 26, dtype=float).reshape(5, 5)
w = s(x, (3, 3))
y = w.mean(axis=(2, 3))
print(y)


[[ 7.  8.  9.]
 [12. 13. 14.]
 [17. 18. 19.]]
